version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file:
      - ../conf/mongo/mongo-conf.env
    volumes:
      - ../conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../conf/nginx/ssl-certs:/etc/nginx/ssl-certs/
    networks:
      - ${DOCKER_NETWORK}

  dict:
    image: node:10
    working_dir: /working_dir/dict/
    command: node fy-http.js
    restart: always
    env_file:
      - ../conf/mongo/mongo-conf.env
    volumes:
      - ../services/dict:/working_dir/dict/
    networks:
      - ${DOCKER_NETWORK}
  
  mongo:
    image: mongo:4.0.1
    command: ["--auth"]
    restart: always
    env_file:
      - ../conf/mongo/mongo-conf.env
    ports:
      - 27017:27017
    volumes:
      - ../data/db:/data/db/
    networks:
      - ${DOCKER_NETWORK}

networks:
  wx:
    external: true